<?php

namespace Database\Seeders;

use App\Models\WorldCupMatch;
use Illuminate\Database\Seeder;

class MatchesSeeder extends Seeder
{
    public function run(): void
    {
        // Null out all external_ids first to avoid unique constraint conflicts
        WorldCupMatch::query()->update(['external_id' => null]);

        $matches = $this->getMatches();

        foreach ($matches as $match) {
            WorldCupMatch::updateOrCreate(
                ['correlativo' => $match['correlativo']],
                $match
            );
        }

        $this->command->info('Seeded ' . count($matches) . ' matches.');
    }

    private function getMatches(): array
    {
        // match_date stored in America/El_Salvador local time (UTC-6, no DST)
        // external_id = API id from worldcup26.ir (differs from our correlativo order)
        return [
            ['correlativo' =>  1, 'external_id' =>  '1', 'home_team' => 'México',           'home_team_flag' => '🇲🇽', 'away_team' => 'Sudáfrica',       'away_team_flag' => '🇿🇦', 'group_name' => 'Grupo A', 'match_date' => '2026-06-11 13:00:00', 'venue' => 'Ciudad de México',  'stage' => 'group'],
            ['correlativo' =>  2, 'external_id' =>  '2', 'home_team' => 'Corea Del Sur',    'home_team_flag' => '🇰🇷', 'away_team' => 'Rep. Checa',       'away_team_flag' => '🇨🇿', 'group_name' => 'Grupo A', 'match_date' => '2026-06-11 20:00:00', 'venue' => 'Guadalajara',        'stage' => 'group'],
            ['correlativo' =>  3, 'external_id' =>  '3', 'home_team' => 'Canadá',           'home_team_flag' => '🇨🇦', 'away_team' => 'Bosnia Y Herzeg.', 'away_team_flag' => '🇧🇦', 'group_name' => 'Grupo B', 'match_date' => '2026-06-12 13:00:00', 'venue' => 'Toronto',            'stage' => 'group'],
            ['correlativo' =>  4, 'external_id' =>  '4', 'home_team' => 'Estados Unidos',   'home_team_flag' => '🇺🇸', 'away_team' => 'Paraguay',         'away_team_flag' => '🇵🇾', 'group_name' => 'Grupo D', 'match_date' => '2026-06-12 19:00:00', 'venue' => 'Los Angeles',        'stage' => 'group'],
            ['correlativo' =>  5, 'external_id' =>  '8', 'home_team' => 'Catar',            'home_team_flag' => '🇶🇦', 'away_team' => 'Suiza',            'away_team_flag' => '🇨🇭', 'group_name' => 'Grupo B', 'match_date' => '2026-06-13 13:00:00', 'venue' => 'San Francisco',      'stage' => 'group'],
            ['correlativo' =>  6, 'external_id' =>  '7', 'home_team' => 'Brasil',           'home_team_flag' => '🇧🇷', 'away_team' => 'Marruecos',        'away_team_flag' => '🇲🇦', 'group_name' => 'Grupo C', 'match_date' => '2026-06-13 16:00:00', 'venue' => 'N. York/N. Jersey',  'stage' => 'group'],
            ['correlativo' =>  7, 'external_id' =>  '5', 'home_team' => 'Haití',            'home_team_flag' => '🇭🇹', 'away_team' => 'Escocia',          'away_team_flag' => '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'group_name' => 'Grupo C', 'match_date' => '2026-06-13 19:00:00', 'venue' => 'Boston',             'stage' => 'group'],
            ['correlativo' =>  8, 'external_id' =>  '6', 'home_team' => 'Australia',        'home_team_flag' => '🇦🇺', 'away_team' => 'Turquía',          'away_team_flag' => '🇹🇷', 'group_name' => 'Grupo D', 'match_date' => '2026-06-14 22:00:00', 'venue' => 'Vancouver',          'stage' => 'group'],
            ['correlativo' =>  9, 'external_id' => '10', 'home_team' => 'Alemania',         'home_team_flag' => '🇩🇪', 'away_team' => 'Curazao',          'away_team_flag' => '🇨🇼', 'group_name' => 'Grupo E', 'match_date' => '2026-06-14 11:00:00', 'venue' => 'Houston',            'stage' => 'group'],
            ['correlativo' => 10, 'external_id' => '11', 'home_team' => 'Países Bajos',     'home_team_flag' => '🇳🇱', 'away_team' => 'Japón',            'away_team_flag' => '🇯🇵', 'group_name' => 'Grupo F', 'match_date' => '2026-06-14 14:00:00', 'venue' => 'Dallas',             'stage' => 'group'],
            ['correlativo' => 11, 'external_id' =>  '9', 'home_team' => 'Costa De Marfil',  'home_team_flag' => '🇨🇮', 'away_team' => 'Ecuador',          'away_team_flag' => '🇪🇨', 'group_name' => 'Grupo E', 'match_date' => '2026-06-14 17:00:00', 'venue' => 'Filadelfia',         'stage' => 'group'],
            ['correlativo' => 12, 'external_id' => '12', 'home_team' => 'Suecia',           'home_team_flag' => '🇸🇪', 'away_team' => 'Túnez',            'away_team_flag' => '🇹🇳', 'group_name' => 'Grupo F', 'match_date' => '2026-06-14 20:00:00', 'venue' => 'Monterrey',          'stage' => 'group'],
            ['correlativo' => 13, 'external_id' => '14', 'home_team' => 'España',           'home_team_flag' => '🇪🇸', 'away_team' => 'Cabo Verde',       'away_team_flag' => '🇨🇻', 'group_name' => 'Grupo H', 'match_date' => '2026-06-15 10:00:00', 'venue' => 'Atlanta',            'stage' => 'group'],
            ['correlativo' => 14, 'external_id' => '15', 'home_team' => 'Bélgica',          'home_team_flag' => '🇧🇪', 'away_team' => 'Egipto',           'away_team_flag' => '🇪🇬', 'group_name' => 'Grupo G', 'match_date' => '2026-06-15 13:00:00', 'venue' => 'Seattle',            'stage' => 'group'],
            ['correlativo' => 15, 'external_id' => '16', 'home_team' => 'Arabia Saudita',   'home_team_flag' => '🇸🇦', 'away_team' => 'Uruguay',          'away_team_flag' => '🇺🇾', 'group_name' => 'Grupo H', 'match_date' => '2026-06-15 16:00:00', 'venue' => 'Miami',              'stage' => 'group'],
            ['correlativo' => 16, 'external_id' => '13', 'home_team' => 'Irán',             'home_team_flag' => '🇮🇷', 'away_team' => 'Nueva Zelanda',    'away_team_flag' => '🇳🇿', 'group_name' => 'Grupo G', 'match_date' => '2026-06-15 19:00:00', 'venue' => 'Los Angeles',        'stage' => 'group'],
            ['correlativo' => 17, 'external_id' => '17', 'home_team' => 'Francia',          'home_team_flag' => '🇫🇷', 'away_team' => 'Senegal',          'away_team_flag' => '🇸🇳', 'group_name' => 'Grupo I', 'match_date' => '2026-06-16 13:00:00', 'venue' => 'N. York/N. Jersey',  'stage' => 'group'],
            ['correlativo' => 18, 'external_id' => '18', 'home_team' => 'Irak',             'home_team_flag' => '🇮🇶', 'away_team' => 'Noruega',          'away_team_flag' => '🇳🇴', 'group_name' => 'Grupo I', 'match_date' => '2026-06-16 16:00:00', 'venue' => 'Boston',             'stage' => 'group'],
            ['correlativo' => 19, 'external_id' => '19', 'home_team' => 'Argentina',        'home_team_flag' => '🇦🇷', 'away_team' => 'Argelia',          'away_team_flag' => '🇩🇿', 'group_name' => 'Grupo J', 'match_date' => '2026-06-16 19:00:00', 'venue' => 'Kansas City',        'stage' => 'group'],
            ['correlativo' => 20, 'external_id' => '20', 'home_team' => 'Austria',          'home_team_flag' => '🇦🇹', 'away_team' => 'Jordania',         'away_team_flag' => '🇯🇴', 'group_name' => 'Grupo J', 'match_date' => '2026-06-17 22:00:00', 'venue' => 'San Francisco',      'stage' => 'group'],
            ['correlativo' => 21, 'external_id' => '21', 'home_team' => 'Portugal',         'home_team_flag' => '🇵🇹', 'away_team' => 'Rep. Del Congo',   'away_team_flag' => '🇨🇩', 'group_name' => 'Grupo K', 'match_date' => '2026-06-17 11:00:00', 'venue' => 'Houston',            'stage' => 'group'],
            ['correlativo' => 22, 'external_id' => '22', 'home_team' => 'Inglaterra',       'home_team_flag' => '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'away_team' => 'Croacia',          'away_team_flag' => '🇭🇷', 'group_name' => 'Grupo L', 'match_date' => '2026-06-17 14:00:00', 'venue' => 'Dallas',             'stage' => 'group'],
            ['correlativo' => 23, 'external_id' => '24', 'home_team' => 'Ghana',            'home_team_flag' => '🇬🇭', 'away_team' => 'Panamá',           'away_team_flag' => '🇵🇦', 'group_name' => 'Grupo L', 'match_date' => '2026-06-17 17:00:00', 'venue' => 'Toronto',            'stage' => 'group'],
            ['correlativo' => 24, 'external_id' => '23', 'home_team' => 'Uzbekistán',       'home_team_flag' => '🇺🇿', 'away_team' => 'Colombia',         'away_team_flag' => '🇨🇴', 'group_name' => 'Grupo K', 'match_date' => '2026-06-17 20:00:00', 'venue' => 'Ciudad de México',   'stage' => 'group'],
            ['correlativo' => 25, 'external_id' => '28', 'home_team' => 'Rep. Checa',       'home_team_flag' => '🇨🇿', 'away_team' => 'Sudáfrica',        'away_team_flag' => '🇿🇦', 'group_name' => 'Grupo A', 'match_date' => '2026-06-18 10:00:00', 'venue' => 'Atlanta',            'stage' => 'group'],
            ['correlativo' => 26, 'external_id' => '26', 'home_team' => 'Suiza',            'home_team_flag' => '🇨🇭', 'away_team' => 'Bosnia Y Herzeg.', 'away_team_flag' => '🇧🇦', 'group_name' => 'Grupo B', 'match_date' => '2026-06-18 13:00:00', 'venue' => 'Los Angeles',        'stage' => 'group'],
            ['correlativo' => 27, 'external_id' => '27', 'home_team' => 'Canadá',           'home_team_flag' => '🇨🇦', 'away_team' => 'Catar',            'away_team_flag' => '🇶🇦', 'group_name' => 'Grupo B', 'match_date' => '2026-06-18 16:00:00', 'venue' => 'Vancouver',          'stage' => 'group'],
            ['correlativo' => 28, 'external_id' => '25', 'home_team' => 'México',           'home_team_flag' => '🇲🇽', 'away_team' => 'Corea Del Sur',    'away_team_flag' => '🇰🇷', 'group_name' => 'Grupo A', 'match_date' => '2026-06-18 19:00:00', 'venue' => 'Guadalajara',        'stage' => 'group'],
            ['correlativo' => 29, 'external_id' => '31', 'home_team' => 'Estados Unidos',   'home_team_flag' => '🇺🇸', 'away_team' => 'Australia',        'away_team_flag' => '🇦🇺', 'group_name' => 'Grupo D', 'match_date' => '2026-06-19 13:00:00', 'venue' => 'Seattle',            'stage' => 'group'],
            ['correlativo' => 30, 'external_id' => '30', 'home_team' => 'Escocia',          'home_team_flag' => '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'away_team' => 'Marruecos',        'away_team_flag' => '🇲🇦', 'group_name' => 'Grupo C', 'match_date' => '2026-06-19 16:00:00', 'venue' => 'Boston',             'stage' => 'group'],
            ['correlativo' => 31, 'external_id' => '29', 'home_team' => 'Brasil',           'home_team_flag' => '🇧🇷', 'away_team' => 'Haití',            'away_team_flag' => '🇭🇹', 'group_name' => 'Grupo C', 'match_date' => '2026-06-19 18:30:00', 'venue' => 'Filadelfia',         'stage' => 'group'],
            ['correlativo' => 32, 'external_id' => '32', 'home_team' => 'Turquía',          'home_team_flag' => '🇹🇷', 'away_team' => 'Paraguay',         'away_team_flag' => '🇵🇾', 'group_name' => 'Grupo D', 'match_date' => '2026-06-19 21:00:00', 'venue' => 'San Francisco',      'stage' => 'group'],
            ['correlativo' => 33, 'external_id' => '35', 'home_team' => 'Países Bajos',     'home_team_flag' => '🇳🇱', 'away_team' => 'Suecia',           'away_team_flag' => '🇸🇪', 'group_name' => 'Grupo F', 'match_date' => '2026-06-20 11:00:00', 'venue' => 'Houston',            'stage' => 'group'],
            ['correlativo' => 34, 'external_id' => '33', 'home_team' => 'Alemania',         'home_team_flag' => '🇩🇪', 'away_team' => 'Costa De Marfil',  'away_team_flag' => '🇨🇮', 'group_name' => 'Grupo E', 'match_date' => '2026-06-20 14:00:00', 'venue' => 'Toronto',            'stage' => 'group'],
            ['correlativo' => 35, 'external_id' => '34', 'home_team' => 'Ecuador',          'home_team_flag' => '🇪🇨', 'away_team' => 'Curazao',          'away_team_flag' => '🇨🇼', 'group_name' => 'Grupo E', 'match_date' => '2026-06-20 18:00:00', 'venue' => 'Kansas City',        'stage' => 'group'],
            ['correlativo' => 36, 'external_id' => '36', 'home_team' => 'Túnez',            'home_team_flag' => '🇹🇳', 'away_team' => 'Japón',            'away_team_flag' => '🇯🇵', 'group_name' => 'Grupo F', 'match_date' => '2026-06-21 22:00:00', 'venue' => 'Monterrey',          'stage' => 'group'],
            ['correlativo' => 37, 'external_id' => '39', 'home_team' => 'España',           'home_team_flag' => '🇪🇸', 'away_team' => 'Arabia Saudita',   'away_team_flag' => '🇸🇦', 'group_name' => 'Grupo H', 'match_date' => '2026-06-21 10:00:00', 'venue' => 'Atlanta',            'stage' => 'group'],
            ['correlativo' => 38, 'external_id' => '37', 'home_team' => 'Bélgica',          'home_team_flag' => '🇧🇪', 'away_team' => 'Irán',             'away_team_flag' => '🇮🇷', 'group_name' => 'Grupo G', 'match_date' => '2026-06-21 13:00:00', 'venue' => 'Los Angeles',        'stage' => 'group'],
            ['correlativo' => 39, 'external_id' => '40', 'home_team' => 'Uruguay',          'home_team_flag' => '🇺🇾', 'away_team' => 'Cabo Verde',       'away_team_flag' => '🇨🇻', 'group_name' => 'Grupo H', 'match_date' => '2026-06-21 16:00:00', 'venue' => 'Miami',              'stage' => 'group'],
            ['correlativo' => 40, 'external_id' => '38', 'home_team' => 'Nueva Zelanda',    'home_team_flag' => '🇳🇿', 'away_team' => 'Egipto',           'away_team_flag' => '🇪🇬', 'group_name' => 'Grupo G', 'match_date' => '2026-06-21 19:00:00', 'venue' => 'Vancouver',          'stage' => 'group'],
            ['correlativo' => 41, 'external_id' => '43', 'home_team' => 'Argentina',        'home_team_flag' => '🇦🇷', 'away_team' => 'Austria',          'away_team_flag' => '🇦🇹', 'group_name' => 'Grupo J', 'match_date' => '2026-06-22 11:00:00', 'venue' => 'Dallas',             'stage' => 'group'],
            ['correlativo' => 42, 'external_id' => '41', 'home_team' => 'Francia',          'home_team_flag' => '🇫🇷', 'away_team' => 'Irak',             'away_team_flag' => '🇮🇶', 'group_name' => 'Grupo I', 'match_date' => '2026-06-22 15:00:00', 'venue' => 'Filadelfia',         'stage' => 'group'],
            ['correlativo' => 43, 'external_id' => '42', 'home_team' => 'Noruega',          'home_team_flag' => '🇳🇴', 'away_team' => 'Senegal',          'away_team_flag' => '🇸🇳', 'group_name' => 'Grupo I', 'match_date' => '2026-06-22 18:00:00', 'venue' => 'N. York/N. Jersey',  'stage' => 'group'],
            ['correlativo' => 44, 'external_id' => '44', 'home_team' => 'Jordania',         'home_team_flag' => '🇯🇴', 'away_team' => 'Argelia',          'away_team_flag' => '🇩🇿', 'group_name' => 'Grupo J', 'match_date' => '2026-06-22 21:00:00', 'venue' => 'San Francisco',      'stage' => 'group'],
            ['correlativo' => 45, 'external_id' => '45', 'home_team' => 'Portugal',         'home_team_flag' => '🇵🇹', 'away_team' => 'Uzbekistán',       'away_team_flag' => '🇺🇿', 'group_name' => 'Grupo K', 'match_date' => '2026-06-23 11:00:00', 'venue' => 'Houston',            'stage' => 'group'],
            ['correlativo' => 46, 'external_id' => '48', 'home_team' => 'Inglaterra',       'home_team_flag' => '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'away_team' => 'Ghana',            'away_team_flag' => '🇬🇭', 'group_name' => 'Grupo L', 'match_date' => '2026-06-23 14:00:00', 'venue' => 'Boston',             'stage' => 'group'],
            ['correlativo' => 47, 'external_id' => '46', 'home_team' => 'Panamá',           'home_team_flag' => '🇵🇦', 'away_team' => 'Croacia',          'away_team_flag' => '🇭🇷', 'group_name' => 'Grupo L', 'match_date' => '2026-06-23 17:00:00', 'venue' => 'Toronto',            'stage' => 'group'],
            ['correlativo' => 48, 'external_id' => '47', 'home_team' => 'Colombia',         'home_team_flag' => '🇨🇴', 'away_team' => 'Rep. Del Congo',   'away_team_flag' => '🇨🇩', 'group_name' => 'Grupo K', 'match_date' => '2026-06-23 20:00:00', 'venue' => 'Guadalajara',        'stage' => 'group'],
            ['correlativo' => 49, 'external_id' => '54', 'home_team' => 'Suiza',            'home_team_flag' => '🇨🇭', 'away_team' => 'Canadá',           'away_team_flag' => '🇨🇦', 'group_name' => 'Grupo B', 'match_date' => '2026-06-24 13:00:00', 'venue' => 'Vancouver',          'stage' => 'group'],
            ['correlativo' => 50, 'external_id' => '53', 'home_team' => 'Bosnia Y Herzeg.', 'home_team_flag' => '🇧🇦', 'away_team' => 'Catar',            'away_team_flag' => '🇶🇦', 'group_name' => 'Grupo B', 'match_date' => '2026-06-24 13:00:00', 'venue' => 'Seattle',            'stage' => 'group'],
            ['correlativo' => 51, 'external_id' => '49', 'home_team' => 'Escocia',          'home_team_flag' => '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'away_team' => 'Brasil',           'away_team_flag' => '🇧🇷', 'group_name' => 'Grupo C', 'match_date' => '2026-06-24 16:00:00', 'venue' => 'Miami',              'stage' => 'group'],
            ['correlativo' => 52, 'external_id' => '50', 'home_team' => 'Marruecos',        'home_team_flag' => '🇲🇦', 'away_team' => 'Haití',            'away_team_flag' => '🇭🇹', 'group_name' => 'Grupo C', 'match_date' => '2026-06-24 16:00:00', 'venue' => 'Atlanta',            'stage' => 'group'],
            ['correlativo' => 53, 'external_id' => '52', 'home_team' => 'Rep. Checa',       'home_team_flag' => '🇨🇿', 'away_team' => 'México',           'away_team_flag' => '🇲🇽', 'group_name' => 'Grupo A', 'match_date' => '2026-06-24 19:00:00', 'venue' => 'Ciudad de México',   'stage' => 'group'],
            ['correlativo' => 54, 'external_id' => '51', 'home_team' => 'Sudáfrica',        'home_team_flag' => '🇿🇦', 'away_team' => 'Corea Del Sur',    'away_team_flag' => '🇰🇷', 'group_name' => 'Grupo A', 'match_date' => '2026-06-24 19:00:00', 'venue' => 'Monterrey',          'stage' => 'group'],
            ['correlativo' => 55, 'external_id' => '55', 'home_team' => 'Curazao',          'home_team_flag' => '🇨🇼', 'away_team' => 'Costa De Marfil',  'away_team_flag' => '🇨🇮', 'group_name' => 'Grupo E', 'match_date' => '2026-06-25 14:00:00', 'venue' => 'Filadelfia',         'stage' => 'group'],
            ['correlativo' => 56, 'external_id' => '56', 'home_team' => 'Ecuador',          'home_team_flag' => '🇪🇨', 'away_team' => 'Alemania',         'away_team_flag' => '🇩🇪', 'group_name' => 'Grupo E', 'match_date' => '2026-06-25 14:00:00', 'venue' => 'N. York/N. Jersey',  'stage' => 'group'],
            ['correlativo' => 57, 'external_id' => '59', 'home_team' => 'Japón',            'home_team_flag' => '🇯🇵', 'away_team' => 'Suecia',           'away_team_flag' => '🇸🇪', 'group_name' => 'Grupo F', 'match_date' => '2026-06-25 17:00:00', 'venue' => 'Dallas',             'stage' => 'group'],
            ['correlativo' => 58, 'external_id' => '60', 'home_team' => 'Túnez',            'home_team_flag' => '🇹🇳', 'away_team' => 'Países Bajos',     'away_team_flag' => '🇳🇱', 'group_name' => 'Grupo F', 'match_date' => '2026-06-25 17:00:00', 'venue' => 'Kansas City',        'stage' => 'group'],
            ['correlativo' => 59, 'external_id' => '58', 'home_team' => 'Turquía',          'home_team_flag' => '🇹🇷', 'away_team' => 'Estados Unidos',   'away_team_flag' => '🇺🇸', 'group_name' => 'Grupo D', 'match_date' => '2026-06-25 20:00:00', 'venue' => 'Los Angeles',        'stage' => 'group'],
            ['correlativo' => 60, 'external_id' => '57', 'home_team' => 'Paraguay',         'home_team_flag' => '🇵🇾', 'away_team' => 'Australia',        'away_team_flag' => '🇦🇺', 'group_name' => 'Grupo D', 'match_date' => '2026-06-25 20:00:00', 'venue' => 'San Francisco',      'stage' => 'group'],
            ['correlativo' => 61, 'external_id' => '62', 'home_team' => 'Noruega',          'home_team_flag' => '🇳🇴', 'away_team' => 'Francia',          'away_team_flag' => '🇫🇷', 'group_name' => 'Grupo I', 'match_date' => '2026-06-26 13:00:00', 'venue' => 'Boston',             'stage' => 'group'],
            ['correlativo' => 62, 'external_id' => '61', 'home_team' => 'Senegal',          'home_team_flag' => '🇸🇳', 'away_team' => 'Irak',             'away_team_flag' => '🇮🇶', 'group_name' => 'Grupo I', 'match_date' => '2026-06-26 13:00:00', 'venue' => 'Toronto',            'stage' => 'group'],
            ['correlativo' => 63, 'external_id' => '65', 'home_team' => 'Cabo Verde',       'home_team_flag' => '🇨🇻', 'away_team' => 'Arabia Saudita',   'away_team_flag' => '🇸🇦', 'group_name' => 'Grupo H', 'match_date' => '2026-06-26 18:00:00', 'venue' => 'Houston',            'stage' => 'group'],
            ['correlativo' => 64, 'external_id' => '66', 'home_team' => 'Uruguay',          'home_team_flag' => '🇺🇾', 'away_team' => 'España',           'away_team_flag' => '🇪🇸', 'group_name' => 'Grupo H', 'match_date' => '2026-06-26 18:00:00', 'venue' => 'Guadalajara',        'stage' => 'group'],
            ['correlativo' => 65, 'external_id' => '63', 'home_team' => 'Egipto',           'home_team_flag' => '🇪🇬', 'away_team' => 'Irán',             'away_team_flag' => '🇮🇷', 'group_name' => 'Grupo G', 'match_date' => '2026-06-26 21:00:00', 'venue' => 'Seattle',            'stage' => 'group'],
            ['correlativo' => 66, 'external_id' => '64', 'home_team' => 'Nueva Zelanda',    'home_team_flag' => '🇳🇿', 'away_team' => 'Bélgica',          'away_team_flag' => '🇧🇪', 'group_name' => 'Grupo G', 'match_date' => '2026-06-26 21:00:00', 'venue' => 'Vancouver',          'stage' => 'group'],
            ['correlativo' => 67, 'external_id' => '67', 'home_team' => 'Panamá',           'home_team_flag' => '🇵🇦', 'away_team' => 'Inglaterra',       'away_team_flag' => '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'group_name' => 'Grupo L', 'match_date' => '2026-06-27 15:00:00', 'venue' => 'N. York/N. Jersey',  'stage' => 'group'],
            ['correlativo' => 68, 'external_id' => '68', 'home_team' => 'Croacia',          'home_team_flag' => '🇭🇷', 'away_team' => 'Ghana',            'away_team_flag' => '🇬🇭', 'group_name' => 'Grupo L', 'match_date' => '2026-06-27 15:00:00', 'venue' => 'Filadelfia',         'stage' => 'group'],
            ['correlativo' => 69, 'external_id' => '71', 'home_team' => 'Colombia',         'home_team_flag' => '🇨🇴', 'away_team' => 'Portugal',         'away_team_flag' => '🇵🇹', 'group_name' => 'Grupo K', 'match_date' => '2026-06-27 17:30:00', 'venue' => 'Miami',              'stage' => 'group'],
            ['correlativo' => 70, 'external_id' => '72', 'home_team' => 'Rep. Del Congo',   'home_team_flag' => '🇨🇩', 'away_team' => 'Uzbekistán',       'away_team_flag' => '🇺🇿', 'group_name' => 'Grupo K', 'match_date' => '2026-06-27 17:30:00', 'venue' => 'Atlanta',            'stage' => 'group'],
            ['correlativo' => 71, 'external_id' => '69', 'home_team' => 'Argelia',          'home_team_flag' => '🇩🇿', 'away_team' => 'Austria',          'away_team_flag' => '🇦🇹', 'group_name' => 'Grupo J', 'match_date' => '2026-06-27 20:00:00', 'venue' => 'Kansas City',        'stage' => 'group'],
            ['correlativo' => 72, 'external_id' => '70', 'home_team' => 'Jordania',         'home_team_flag' => '🇯🇴', 'away_team' => 'Argentina',        'away_team_flag' => '🇦🇷', 'group_name' => 'Grupo J', 'match_date' => '2026-06-27 20:00:00', 'venue' => 'Dallas',             'stage' => 'group'],
        ];
    }
}
