[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700
chown=www-data:www-data

[supervisord]
nodaemon=true
logfile=/var/www/html/storage/logs/supervisord-worker.log
pidfile=/tmp/supervisord-worker.pid
childlogdir=/var/www/html/storage/logs

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:horizon]
command=php artisan horizon
user=www-data
environment=HOME="/var/www/html"
directory=/var/www/html
autostart=true
autorestart=true
startretries=3
numprocs=1
stderr_logfile=/var/www/html/storage/logs/horizon.err.log
stdout_logfile=/var/www/html/storage/logs/horizon.out.log
priority=10

[program:scheduler]
command=php /var/www/html/artisan schedule:work
user=www-data
directory=/var/www/html
autostart=true
autorestart=true
startretries=3
numprocs=1
stderr_logfile=/var/www/html/storage/logs/scheduler.err.log
stdout_logfile=/var/www/html/storage/logs/scheduler.out.log
priority=20

[program:pulse-worker]
command=php artisan pulse:work
user=www-data
directory=/var/www/html
autostart=true
autorestart=true
startretries=3
numprocs=1
stderr_logfile=/var/www/html/storage/logs/pulse.err.log
stdout_logfile=/var/www/html/storage/logs/pulse.out.log
priority=30
