[program:worker-laravel]
process_name=%(program_name)s_%(process_num)02d
command=php -d memory_limit=256M /var/www/html/artisan queue:work --queue=import,default --sleep=3 --tries=3 --max-jobs=100 --timeout=-1 --no-interaction
directory=/var/www/html
autostart=true
autorestart=true
numprocs=1
startretries=3
startsecs=1
stdout_logfile=/var/www/html/storage/logs/worker.log
stderr_logfile=/var/www/html/storage/logs/worker.log
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
