[program:pulse-worker]
process_name=%(program_name)s
command=php /var/www/html/artisan pulse:work
directory=/var/www/html
autostart=true
autorestart=true
numprocs=1
startretries=3
startsecs=1
stdout_logfile=/var/www/html/storage/logs/pulse-worker.log
stderr_logfile=/var/www/html/storage/logs/pulse-worker.log
stdout_logfile_maxbytes=100MB
stderr_logfile_maxbytes=100MB
stdout_logfile_backups=5
stderr_logfile_backups=5
